#连接redis
spring:
  redis:
    host: 192.168.247.128
    port: 6379
#MySQL数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
